[tool.poetry]
name = "com.valvesoftware.Steam"
description = "Boilerplate for managing dependencies"
version = "1.0.0"
authors = [
    "Flathub"
]

[tool.poetry.dependencies]
python = "3.8"
jsonschema = "*"
PyYAML = "*"
vdf = "*"
