#!/bin/bash

set -eu

if ! [ -s /etc/ld.so.conf ]; then
    # Fallback for flatpak < 0.9.99
    export LD_LIBRARY_PATH=/app/lib:/app/lib/32bit/lib
    export STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0
fi

# Migration from when $HOME used to be overridden:
_STEAM_HOME="$HOME/.var/app/com.valvesoftware.Steam/home"
if [ -d $_STEAM_HOME ]; then
    set -x
    GLOBIGNORE="*/.steam:*/.local:*/.var"
    cp -a $_STEAM_HOME/* $HOME/
    rm -r $_STEAM_HOME
    unset GLOBIGNORE
    set +x
fi

# Workaround for the fact many games, and Steam itself,
# hardcode xdg paths to the defaults.
_STEAM_BASE="$HOME/.var/app/com.valvesoftware.Steam"
_CONFIG_DIR=.config
_CONFIG=$_STEAM_BASE/$_CONFIG_DIR
_DATA_DIR=.local/share
_DATA=$_STEAM_BASE/$_DATA_DIR
_CACHE_DIR=.cache
_CACHE=$_STEAM_BASE/$_CACHE_DIR

mkdir -p $_CACHE $_CONFIG $_DATA

# Migrate any old data:
if [ ! -L $XDG_CONFIG_HOME ]; then
  cp -a $XDG_CONFIG_HOME/* $_CONFIG
  # You can't delete $XDG_CONFIG_HOME/user-dirs.dirs
  mv $XDG_CONFIG_HOME ${XDG_CONFIG_HOME}.remove_me
  ln -s $_CONFIG_DIR $XDG_CONFIG_HOME
elif [ -d ${XDG_CONFIG_HOME}.remove_me ]; then
  rm -r ${XDG_CONFIG_HOME}.remove_me
fi
if [ ! -L $XDG_DATA_HOME ]; then
  mv $XDG_DATA_HOME/Steam $_DATA
  cp -a $XDG_DATA_HOME/* $_DATA
  rm -r $XDG_DATA_HOME
  ln -s $_DATA_DIR $XDG_DATA_HOME
fi
if [ ! -L $XDG_CACHE_HOME ]; then
  cp -a $XDG_CACHE_HOME/* $_CACHE
  rm -r $XDG_CACHE_HOME
  ln -s $_CACHE_DIR $XDG_CACHE_HOME
fi

export XDG_DATA_HOME=$_DATA
export XDG_CONFIG_HOME=$_CONFIG
export XDG_CACHE_HOME=$_CACHE

exec /app/bin/steam "$@"
